import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "innovation-purple": "#6B46C1",
        "surface-tint": "#455f88",
        "on-primary-fixed": "#001b3c",
        "outline-variant": "#c4c6cf",
        "university-blue": "#1A365D",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#271900",
        "outline": "#74777f",
        "secondary-fixed": "#ffdeaa",
        "on-background": "#191c1e",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#5f4100",
        "inverse-surface": "#2d3133",
        "on-surface-variant": "#43474e",
        "primary-fixed-dim": "#adc7f7",
        "tertiary-container": "#410f96",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#23005c",
        "tertiary": "#290069",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e9ddff",
        "surface-container": "#eceef0",
        "on-primary-fixed-variant": "#2d476f",
        "on-error": "#ffffff",
        "surface-white": "#FFFFFF",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#725000",
        "primary-fixed": "#d6e3ff",
        "secondary-container": "#ffc250",
        "inverse-on-surface": "#eff1f3",
        "surface-variant": "#e0e3e5",
        "primary": "#002045",
        "on-tertiary-fixed-variant": "#522aa7",
        "slate-500": "#64748B",
        "on-primary-container": "#86a0cd",
        "secondary-fixed-dim": "#f8bc4b",
        "on-primary": "#ffffff",
        "surface": "#f7f9fb",
        "academic-gold": "#D69E2E",
        "slate-900": "#0F172A",
        "tertiary-fixed-dim": "#d0bcff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ac8bff",
        "primary-container": "#1a365d",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#adc7f7",
        "secondary": "#7d5700",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        "container-max": "1280px",
        "gutter": "24px",
        "stack-md": "16px",
        "unit": "4px",
        "stack-xl": "48px",
        "stack-lg": "24px",
        "stack-xs": "4px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "title-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-montserrat)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        }
      },
      animation: {
        "fade-in": "fade-in 0.8s ease-out forwards",
      }
    },
  },
  plugins: [],
};
export default config;
